make_diff_pair_ports rxp[0] rxn[0]
make_diff_pair_ports rxp[1] rxn[1]
make_diff_pair_ports rxp[2] rxn[2]
make_diff_pair_ports rxp[3] rxn[3]
make_diff_pair_ports FPGA_JESD_CLKP FPGA_JESD_CLKM
make_diff_pair_ports CLK_LAO_0P CLK_LAO_0M
make_diff_pair_ports FPGA_JESD_SYSREFP FPGA_JESD_SYSREFM
make_diff_pair_ports SYNCbABP SYNCbABM
make_diff_pair_ports SYNCbCDP SYNCbCDM
set_property IOSTANDARD LVDS_25 [get_ports {rxp[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {rxp[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {rxp[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {rxp[3]}]
set_property PACKAGE_PIN B6 [get_ports {rxp[0]}]
set_property PACKAGE_PIN B5 [get_ports {rxn[0]}]
set_property PACKAGE_PIN C4 [get_ports {rxp[1]}]
set_property PACKAGE_PIN C3 [get_ports {rxn[1]}]
set_property PACKAGE_PIN E4 [get_ports {rxp[2]}]
set_property PACKAGE_PIN E3 [get_ports {rxn[2]}]
set_property PACKAGE_PIN G4 [get_ports {rxp[3]}]
set_property PACKAGE_PIN G3 [get_ports {rxn[3]}]
set_property PACKAGE_PIN H16 [get_ports JESD_SYNC]
set_property IOSTANDARD LVDS_25 [get_ports FPGA_JESD_CLKP]
set_property PACKAGE_PIN D6 [get_ports FPGA_JESD_CLKP]
set_property PACKAGE_PIN D5 [get_ports FPGA_JESD_CLKM]
set_property PACKAGE_PIN H17 [get_ports CLK_LAO_0P]
set_property PACKAGE_PIN H18 [get_ports CLK_LAO_0M]
set_property PACKAGE_PIN A18 [get_ports FPGA_JESD_SYSREFP]
set_property PACKAGE_PIN A19 [get_ports FPGA_JESD_SYSREFM]
set_property PACKAGE_PIN F19 [get_ports SYNCbABP]
set_property PACKAGE_PIN E20 [get_ports SYNCbABM]
set_property PACKAGE_PIN G12 [get_ports SYNCbCDP]
set_property PACKAGE_PIN F12 [get_ports SYNCbCDM]
set_property DIRECTION IN [get_ports {rxp[0]}]
set_property DIRECTION IN [get_ports {rxp[1]}]
set_property DIRECTION IN [get_ports {rxp[2]}]
set_property DIRECTION IN [get_ports {rxp[3]}]
set_property DIRECTION IN [get_ports {rxn[0]}]
set_property DIRECTION IN [get_ports {rxn[1]}]
set_property DIRECTION IN [get_ports {rxn[2]}]
set_property DIRECTION IN [get_ports {rxn[3]}]
set_property DIRECTION OUT [get_ports JESD_SYNC]
set_property IOSTANDARD LVCMOS25 [get_ports JESD_SYNC]
set_property DRIVE 12 [get_ports JESD_SYNC]
set_property SLEW SLOW [get_ports JESD_SYNC]
set_property DIRECTION IN [get_ports FPGA_JESD_CLKP]
set_property DIRECTION IN [get_ports FPGA_JESD_CLKM]
set_property DIRECTION IN [get_ports CLK_LAO_0P]
set_property IOSTANDARD LVDS_25 [get_ports CLK_LAO_0P]
set_property DIRECTION IN [get_ports CLK_LAO_0M]
set_property IOSTANDARD LVDS_25 [get_ports CLK_LAO_0M]
set_property DIRECTION IN [get_ports FPGA_JESD_SYSREFP]
set_property IOSTANDARD LVDS_25 [get_ports FPGA_JESD_SYSREFP]
set_property DIRECTION IN [get_ports FPGA_JESD_SYSREFM]
set_property IOSTANDARD LVDS_25 [get_ports FPGA_JESD_SYSREFM]
set_property DIRECTION OUT [get_ports SYNCbABP]
set_property IOSTANDARD LVDS_25 [get_ports SYNCbABP]
set_property DIRECTION OUT [get_ports SYNCbABM]
set_property IOSTANDARD LVDS_25 [get_ports SYNCbABM]
set_property DIRECTION OUT [get_ports SYNCbCDP]
set_property IOSTANDARD LVDS_25 [get_ports SYNCbCDP]
set_property DIRECTION OUT [get_ports SYNCbCDM]
set_property IOSTANDARD LVDS_25 [get_ports SYNCbCDM]
#revert back to original instance
current_instance -quiet
