# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/k410t_jesd_pin_planning/io_1.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_frontpanel_0_0/design_1_frontpanel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_frontpanel_0_0 || ORIG_REF_NAME==design_1_frontpanel_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_jesd204_0_0/design_1_jesd204_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_jesd204_0_0 || ORIG_REF_NAME==design_1_jesd204_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_okAXI4LiteInterface_0_0/design_1_okAXI4LiteInterface_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_okAXI4LiteInterface_0_0 || ORIG_REF_NAME==design_1_okAXI4LiteInterface_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_0_0/design_1_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_0_0 || ORIG_REF_NAME==design_1_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_wireoutbreakout_0_0/design_1_wireoutbreakout_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_wireoutbreakout_0_0 || ORIG_REF_NAME==design_1_wireoutbreakout_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_1_0/design_1_util_ds_buf_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_1_0 || ORIG_REF_NAME==design_1_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_2_0/design_1_util_ds_buf_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_2_0 || ORIG_REF_NAME==design_1_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ila_0_1/design_1_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ila_0_1 || ORIG_REF_NAME==design_1_ila_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_data_processing_unit_0_0/design_1_data_processing_unit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_data_processing_unit_0_0 || ORIG_REF_NAME==design_1_data_processing_unit_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_jesd204_0_transport_0_0/design_1_jesd204_0_transport_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_jesd204_0_transport_0_0 || ORIG_REF_NAME==design_1_jesd204_0_transport_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
