# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/design_1_jesd204_0_0.xci
# IP: The module: 'design_1_jesd204_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/ip_0/design_1_jesd204_0_0_phy.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_jesd204_0_0_phy || ORIG_REF_NAME==design_1_jesd204_0_0_phy} -quiet] -quiet

# IP: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/ip_0/ip_0/design_1_jesd204_0_0_phy_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_jesd204_0_0_phy_gt || ORIG_REF_NAME==design_1_jesd204_0_0_phy_gt} -quiet] -quiet

# XDC: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/ip_0/ip_0/design_1_jesd204_0_0_phy_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_jesd204_0_0_phy_gt || ORIG_REF_NAME==design_1_jesd204_0_0_phy_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/ip_0/ip_0/design_1_jesd204_0_0_phy_gt_ooc.xdc

# XDC: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/ip_0/synth/design_1_jesd204_0_0_phy_ooc.xdc

# XDC: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/ip_0/synth/design_1_jesd204_0_0_phy.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_jesd204_0_0_phy || ORIG_REF_NAME==design_1_jesd204_0_0_phy} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/ip_0/synth/design_1_jesd204_0_0_phy_clock_group.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_jesd204_0_0_phy || ORIG_REF_NAME==design_1_jesd204_0_0_phy} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/ip_0/synth/design_1_jesd204_0_0_phy_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_jesd204_0_0_phy || ORIG_REF_NAME==design_1_jesd204_0_0_phy} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/synth/design_1_jesd204_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_jesd204_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/synth/design_1_jesd204_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_jesd204_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/design_1_jesd204_0_0.xci
# IP: The module: 'design_1_jesd204_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/ip_0/design_1_jesd204_0_0_phy.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_jesd204_0_0_phy || ORIG_REF_NAME==design_1_jesd204_0_0_phy} -quiet] -quiet

# IP: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/ip_0/ip_0/design_1_jesd204_0_0_phy_gt.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_jesd204_0_0_phy_gt || ORIG_REF_NAME==design_1_jesd204_0_0_phy_gt} -quiet] -quiet

# XDC: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/ip_0/ip_0/design_1_jesd204_0_0_phy_gt.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_jesd204_0_0_phy_gt || ORIG_REF_NAME==design_1_jesd204_0_0_phy_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/ip_0/ip_0/design_1_jesd204_0_0_phy_gt_ooc.xdc

# XDC: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/ip_0/synth/design_1_jesd204_0_0_phy_ooc.xdc

# XDC: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/ip_0/synth/design_1_jesd204_0_0_phy.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_jesd204_0_0_phy || ORIG_REF_NAME==design_1_jesd204_0_0_phy} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/ip_0/synth/design_1_jesd204_0_0_phy_clock_group.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_jesd204_0_0_phy || ORIG_REF_NAME==design_1_jesd204_0_0_phy} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/ip_0/synth/design_1_jesd204_0_0_phy_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_jesd204_0_0_phy || ORIG_REF_NAME==design_1_jesd204_0_0_phy} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/synth/design_1_jesd204_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_jesd204_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /users/wstoy/Documents/vivado/projects/k410t_jesd/k410t_jesd.srcs/sources_1/bd/design_1/ip/design_1_jesd204_0_0/synth/design_1_jesd204_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_jesd204_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
